[workspace]
members = ["payjoin", "payjoin-cli", "payjoin-directory", "payjoin-test-utils", "payjoin-ffi"]
resolver = "2"

[profile.release-smaller]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
strip = true

[patch.crates-io]
payjoin = { path = "payjoin" }
payjoin-directory = { path = "payjoin-directory" }
payjoin-test-utils = { path = "payjoin-test-utils" }